InternalClassType: DataTable
Origin: 3e87a345-7c89-40d6-b74b-d643ad2ad6d4
RandomSeed: 1073747470
UUID: 01a0236c-0546-7520-956c-ec4f12b5276d
3D:
 NameLabelEnabled: true
 NameLabelPosition: [0,-2,0.02]
 NameLabelRotation: [0,0,0,-1]
 NameLabelScale: [1,1,1]
 VisibleGraphicGroups: ["Default"]
$Data:
