InternalClassType: Dialog
Label: "Advanced Settings in  'Assembly2'"
Origin: 520bde3e-70c0-4bb9-99f8-2fdc29373acb
RandomSeed: 1073747561
UUID: 01a0236c-0546-756a-a433-40eeac645929
$CustomAttributes:
-
 Name: ExpNo
 ID: 10
 $DataType: integer
 Value: 1
-
 Name: ObservNo
 ID: 11
 $DataType: integer
 Value: 1
$Elements:
-
 Type: TabControl
 Name: "Tab"
 $Elements:
 -
  Type: TabPage
  Name: "Settings"
  $Elements:
  -
   Type: GroupBox
   Name: "UserMethods_Gr"
   $Elements:
   -
    Type: Button
    Name: "ConfigMethod_but"
    Enable: false
   -
    Type: Button
    Name: "SeedValues_but"
    Enable: false
   -
    Type: Button
    Name: "EvalMethod_but"
    Enable: false
  -
   Type: GroupBox
   Name: "reliability_Gr"
   $Elements:
   -
    Type: EditText
    Name: "ConfLevel_I"
    Caption: "90"
  -
   Type: GroupBox
   Name: "restore_GR"
   $Elements:
   -
    Type: CheckBox
    Name: "restore_CB"
    IsChecked: true
 -
  Type: TabPage
  Name: "Validation"
 -
  Type: TabPage
  Name: "DistSim"
 -
  Type: TabPage
  Name: "Rules"
  $Elements:
  -
   Type: GroupBox
   Name: "Rules_GR"
   $Elements:
   -
    Type: EditText
    Name: "Prio_Input"
    Caption: "3"
    Enable: false
 -
  Type: TabPage
  Name: "Report"
  $Elements:
  -
   Type: GroupBox
   Name: "Descript_Gr"
   $Elements:
   -
    Type: EditText
    Name: "ProjName_Inp"
    Caption: "Small Parts Production"
   -
    Type: EditText
    Name: "ProjPers_Inp"
    Caption: "Simulation Expert"
